### PR TITLE
Merge develop to master

### PR DESCRIPTION
**Pull request by brilliant-lx**
Mainly some documents updated and a feature: https://github.com/bnb-chain/bsc-genesis-contract/pull/299

### CODE REVIEW

**Comment by buddh0** [comment]
image
are these two PRs existed in master branch？

**Comment by brilliant-lx** [comment]
> 

I think it is ok, the 2 existed PRs will be eliminated by github merge automatically.

**Review by cosinlink — APPROVED** [review]

**Review by guagualvcha — APPROVED** [review]

**Review by cosinlink — APPROVED** [review]

**Review by Hsenaai — COMMENTED** [review]
A

**Review by Hsenaai — COMMENTED** [review]
A

**Review by Hsenaai — COMMENTED** [review]
A

**Review by Hsenaai — COMMENTED** [review]
A

**Review by behzad1191 — APPROVED** [review]

**Pull request merged**
