### PR TITLE
feat: modify repo structure and rename contracts

### PR DESCRIPTION
**Pull request by cosinlink**
* feat: modify repo structure and rename BC_fusion/System.sol to SystemV2.sol

* feat: modify genesis generate script since repo structure changed

* chores: modify lint cmt to fit repo structure changes

* chores: lint contracts code

* feat: add deprecated folder and move some contracts to it

* fix: genesis generate script

* fix: update foundry toolchain version

* chores: lint contracts

* feat: remove BC_fusion folder and move contracts to root dir

* fix: genesis generate script

* chores: modify fmt script

* chores: modify foundry toolchain

* feat: rename lib and interface folder

* feat: remove unused BEP20Token.template

* feat: remove unused mock

### Description

add a description of your changes here...

### Rationale

tell us why we need these changes...

### Example

add an example CLI or API response...

### Changes

Notable changes:
* add each change in a bullet point here
* ...

### CODE REVIEW

**Review by OKEAMAH — APPROVED** [review]
Cool

**Review by OKEAMAH — APPROVED** [review]
Great

**Review by unclezoro — APPROVED** [review]

**Review by pythonberg1997 — APPROVED** [review]

**Comment by NathanBSC** [comment]
abi files need clear up?

**Comment by NathanBSC** [comment]
cool!

**Review by NathanBSC — APPROVED** [review]

**Pull request merged**
